language: java
jdk:
  - openjdk8

branches:
  only:
    - main

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"


before_install:
  - chmod +x ./gradlew

before_deploy:
  - zip -r springboot_AWS *
  - mkdir -p deploy
  - mv springboot_AWS.zip deploy/springboot_AWS.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #Travis repo setting에 설정된 값
    secret_access_key: $AWS_SECRET_KEY #Travis repo setting설정값
    bucket: freelec-springboot-build #s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #zip 파일 접근 private
    local_dir: deploy #before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build
    key: springboot_AWS.zip #빌드파일을 압축해서 전달
    build_type: zip #압축 확장자
    application: freelec-springboot2-webservice #웹 콘솔에서 등록한 CodeDeploy 애플리케이션
    deployment-group: freelec-springboot2-webservice-group #웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - laveberry7@gmail.com
